// info of the object to be transfered->Data transfer object -Book
class IssuedBook{
    // Class name should start with capital letter
    // id is autogenerated  if id it means that id is also paased in obj
    _id;
    name;
    genre;
    price;
    publisher;
    issuedBy;
    issuedDate;
    returnDate;

// whenever the obj is created the constructor or method is auto called/invoked
// parameterized constructor ,It should always be within the class 
// constructor does not return a type ->does not return anything,no need to write class name

constructor (user){
//    transfer data from user obj to book obj since info related to books is in user table
// right user obj and left:->book obj  , this points to current obj
this._id=user.IssuedBook._id;
this.name=user.IssuedBook.name;
this.genre=user.IssuedBook.genre;
this.price=user.IssuedBook.price;
this.publisher=user.IssuedBook.publisher;

// only present in user not in book ->directly assign from user
this.issuedBy=user.issuedBy;
this.issuedDate = user.issuedDate;
this.returnDate = user.returnDate;
}
}
// var ref=new IssuedBook(userObj)

module.exports=IssuedBook;


